### ISSUE TITLE
Vec3 field is not scriptable

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#128]
<img src='https://shipusercontent.com/96d2f003ed772817f420c22fa4e2354a/Screen%20Shot%202017-08-29%20at%2012.03.33%20copy.jpg' title='Screen Shot 2017-08-29 at 12.03.33 copy.jpg' width=161>

**Comment by vorg** [comment]
Turns out I was creating params with type "PARA"

```
graph.port(graph.IN, graph.PARA, 'name', [0, 0, 0])
```

Changing it to "PARAM" makes port scriptable again
```
graph.port(graph.IN, graph.PARAM, 'name', [0, 0, 0])
```

**Comment by vorg** [comment]
This has to use different syntax or be validated

**Comment by nicknikolov** [comment]
See pex-gl/pex-nodes#120
