### ISSUE TITLE
Scriptable params

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-nodes#13]
Instead of exposing colors and vectors and numbers params should have script boxes which converts incoming number values to whatever type they are.

Example:
- Repeater to Color `[$/2, 1, $/10, 1]`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

**Comment by vorg** [comment]
We could inject built-in function using the following:

```javascript
const params = ['$']
const expr = '[$/2, 1, sin($/10), 1]' 
const body = `
  const sin = Math.sin
  const abs = Math.abs
  ...
  return ${expr}
`

// this should be cached until `expr` changes
const fn = new Function(params, body)
return fn(value)
```
