### ISSUE TITLE
Swipe node onto a link

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#141]
In Houdini you can drag node on a link to inject it between two other nodes

<img width="600" alt="screen shot 2017-10-03 at 12 23 48" src="https://user-images.githubusercontent.com/171001/31123167-a980bc92-a836-11e7-8968-f4880506b8da.png">

https://vimeo.com/210226436

**Comment by nicknikolov** [comment]
Moved to worklfowy
