### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#15]
Currently the package.json says we are at `1.0.0` this would probably be changed to `0.0.1` and be bumped to `0.1.0` with first milestone.

This will become important later when we save projects agains a particular version that should be able to be recovered from npm if needed to run that project again.

**Comment by nicknikolov** [comment]
Answer: currently developed as 0.x, with breaking changes. Once clients gets split off from server and standalone it will become 1.0 and we track breaking changes using major versions
