### ISSUE TITLE
Style inspector top bar

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-nodes#152]

**Comment by vorg** [comment]
Before

<img src='https://shipusercontent.com/9b67167521bd2e584bbeb09016bd2189/Screen%20Shot%202017-10-20%20at%2023.25.25.png' title='Screen Shot 2017-10-20 at 23.25.25.png' width=84>

**Comment by vorg** [comment]
Fixed in 35fbcb4b5835363e959b8edde8e755e3e51f7ce4

**Comment by vorg** [comment]
After <img src='https://shipusercontent.com/e5f769049707a6fc932c92f21bfd874a/Screen%20Shot%202017-10-20%20at%2023.40.54.png' title='Screen Shot 2017-10-20 at 23.40.54.png' width=616>
