### ISSUE TITLE
Everything is a custom node

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-nodes#22]
Maybe everything is a custom node, just built-in ones are provided with specific code, but you can double click+edit+saveas to a different name and voala, you extended vocabulary in-line.

**Comment by vorg** [comment]
This could work if we don't require any modules. I always thought the built-in nodes are `sealed` and can't be edited. E.g. I would rather not copy-paste 1000 LOC gltf parser into custom node. Saying that `vtg` (vorg texture generator) could be distributed as a "library" aka collection of custom nodes.

**Comment by nicknikolov** [comment]
https://gist.github.com/mathisonian/c325dbe02ea4d6880c4e
