### ISSUE TITLE
Export scene container is not fullscreen

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#232]
<img src='https://shipusercontent.com/048c2c3e21a19276c69cf83d58957ac4/Screen%20Shot%202018-02-13%20at%2013.43.33.png' title='Screen Shot 2018-02-13 at 13.43.33.png' width=243>

This causes issues like half window canvas?
<img src='https://shipusercontent.com/49f9a425b6f45107c76186796cae8262/Screen%20Shot%202018-02-13%20at%2010.16.46.jpg' title='Screen Shot 2018-02-13 at 10.16.46.jpg' width=754>

And infinitely growing scene where scene canvas is based on scene container size and they keep increasing each other by 1px

**Comment by vorg** [comment]
So there is couple of problems:

1. We don't include tachyons in export
To fix it I can move css('tachyons') from Inspector to index.js and export.index.js but then font size changes?

<img src='https://shipusercontent.com/74d645be4557a44ac6be587e065fa1cc/Screen%20Shot%202018-02-13%20at%2016.05.34.jpg' title='Screen Shot 2018-02-13 at 16.05.34.jpg' width=168>
<img src='https://shipusercontent.com/c8bf9ede2b75bc7e6cef43424cd263ee/Screen%20Shot%202018-02-13%20at%2016.05.34.jpg' title='Screen Shot 2018-02-13 at 16.05.34.jpg' width=168>

2. Somehow canvas height is in subpixels that bumps container height by 1 pixel which gives canvas space to grow one pixel which expands container and so on

<img src='https://shipusercontent.com/2734ae124b14ccddd213369ea0f963db/Screen%20Shot%202018-02-13%20at%2016.09.38.png' title='Screen Shot 2018-02-13 at 16.09.38.png' width=187>

**Comment by vorg** [comment]
Adding height: 100% to body with `<body class="h-100">` in index.export.js fixes infinitely expanding canvas. Just need to check what changed the font size.

**Comment by nicknikolov** [comment]
1. Does moving tachyons really change font size? Even so we can just add it export.index.js, then we won't have that issue

**Comment by vorg** [comment]
<img src='https://shipusercontent.com/e3c7926ceb53a4efbcb1bc41bf050858/Screen%20Shot%202018-02-13%20at%2016.20.38.png' title='Screen Shot 2018-02-13 at 16.20.38.png' width=198>

Yes, it does. maybe we have two version of tachyons included? Hard to pintpoint with 100k lines of CSS in one line..

**Comment by vorg** [comment]
Ok. There we go. Menu bar overwrites tachyons class https://github.com/pex-gl/pex-nodes/blob/master/components/shell/menu-bar.js#L48

**Comment by nicknikolov** [comment]
Right...
