### ISSUE TITLE
Slider shrunk after moving tachyons import around

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#238]
Old
<img src='https://shipusercontent.com/a2061ba85efac86ee8d2aa83101a3b17/Screen%20Shot%202018-02-13%20at%2016.33.48.png' title='Screen Shot 2018-02-13 at 16.33.48.png' width=432>

New
<img src='https://shipusercontent.com/040cf337b9e6d067213fa7f7844f778c/Screen%20Shot%202018-02-13%20at%2016.33.28.png' title='Screen Shot 2018-02-13 at 16.33.28.png' width=348>

**Comment by vorg** [comment]
@nicknikolov do you remember why `.range` class sets with to 25% and next to it we have `w-100` anyway?


<img src='https://shipusercontent.com/f8e0bd07f8cf96b6da1123458c939306/Screen%20Shot%202018-02-13%20at%2016.36.53.png' title='Screen Shot 2018-02-13 at 16.36.53.png' width=373>

<img src='https://shipusercontent.com/d21122dcb6ee5138a5589f1a81cdd76f/Screen%20Shot%202018-02-13%20at%2016.37.03.png' title='Screen Shot 2018-02-13 at 16.37.03.png' width=171>

**Comment by nicknikolov** [comment]
so this is part of how pex-html gui works I think. All the inside elements are w-100 and parent gets some percentage or whatever from 
https://github.com/pex-gl/pex-nodes/blob/master/components/graph-editor/inspector/layout.js#L2

**Comment by nicknikolov** [comment]
But actually not sure where this 25 come from

**Comment by vorg** [comment]
Fixed in 1a19317
