### ISSUE TITLE
Revive app.log

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-nodes#245]

**Comment by vorg** [comment]
What was this about?

**Comment by vorg** [comment]
This also reminds me how much we depend on devtools console for debugging, checking data etc... would be good to have some first class support for those use cases.

**Comment by nicknikolov** [comment]
Added back in https://github.com/pex-gl/pex-nodes/commit/c6249ce825615a8d999bb8d1002493592af4ef3b
