### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-nodes#25]
- Selecting
- Connecting
- Deleting
etc...

- [ ] Needs to be expanded and described in more detail.
- [ ] Need to push my keyboard shortcuts branch

**Comment by vorg** [comment]
Use dot products to find nearest node in the 90' viewport in the given direction

![screen shot 2017-03-16 at 17 32 34](https://cloud.githubusercontent.com/assets/171001/24011716/7013ad22-0a73-11e7-84c9-c267c221763e.png)
