### ISSUE TITLE
Add proper color control for comment colors

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#276]
After switching to bright theme all comments are super dark.
<img width="401" alt="screen shot 2018-04-30 at 12 14 23" src="https://user-images.githubusercontent.com/171001/39424961-0d422f52-4c71-11e8-9e34-a73134c34c49.png">

Our gui accepts only hex colors without ability to specify alpha.

<img width="387" alt="screen shot 2018-04-30 at 12 22 04" src="https://user-images.githubusercontent.com/171001/39424990-28f05080-4c71-11e8-87ce-9c0ee16e23b6.png">

Having proper alpha doesn't mean we use expensive ctx.globalAlpha, we can use Color.lerp to create "transparent" color manually.

**Comment by nicknikolov** [comment]
Added RGB, more will come when we make generic pex nodes components
