### ISSUE TITLE
Improve graph canvas rendering performance

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-nodes#280]
Ideas:
- batching: draw all active nodes backgrounds at once, draw all green links at once etc.
- draw only objects visible in the viewport
- simplified mode at certain zoom level: no text beside comments (maybe just rectangles), thicker lines, more prominent errors

**Comment by nicknikolov** [comment]
- webgl :D

**Comment by vorg** [comment]
Test1. Without batching (beginPath/rect for each port) 10ms, with batching (one beginPath) 500ms... turns out:

> with Canvas, there’s an important exception to this rule: if the primitives involved in drawing the desired object have small bounding boxes (for example, horizontal and vertical lines), it may actually be more efficient to render them separately 

Source: https://www.html5rocks.com/en/tutorials/canvas/performance/
